[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "day1"
path = "src/aoc2024/day1.rs"

[[bin]]
name = "day1_2"
path = "src/aoc2024/day1_2.rs"

[[bin]]
name = "day2"
path = "src/aoc2024/day2.rs"

[dependencies]
